//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zen.Trunk.Torrent.Repository
{
    using System;
    
    public enum RemoteControlDeviceType : short
    {
        DesktopBrowser = 0,
        MobileBrowser = 1,
        AndroidPhone = 2,
        BlackBerryPhone = 3,
        WindowsPhone = 4,
        ApplePhone = 5
    }
}
