//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zen.Trunk.Torrent.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityNonce
    {
        public System.Guid SecurityNonceId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
