//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zen.Trunk.Torrent.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TorrentModelContainer : DbContext
    {
        public TorrentModelContainer()
            : base("name=TorrentModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TorrentAccount> TorrentAccounts { get; set; }
        public DbSet<TorrentRemoteControl> TorrentRemoteControls { get; set; }
        public DbSet<TorrentAccountAuthorization> TorrentAccountAuthorizations { get; set; }
        public DbSet<TorrentAccountMessage> TorrentAccountMessages { get; set; }
        public DbSet<TorrentRemoteControlMessage> TorrentRemoteControlMessages { get; set; }
        public DbSet<TorrentAccountCertificate> TorrentAccountCertificates { get; set; }
        public DbSet<SecurityNonce> SecurityNonces { get; set; }
    }
}
