//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zen.Trunk.Torrent.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorrentAccount
    {
        public TorrentAccount()
        {
            this.Authorizations = new HashSet<TorrentAccountAuthorization>();
            this.Messages = new HashSet<TorrentAccountMessage>();
        }
    
        public System.Guid TorrentAccountId { get; set; }
        public string ClientAddress { get; set; }
        public string ClientAddressUpdateDate { get; set; }
        public string ClientThumbprint { get; set; }
    
        public virtual ICollection<TorrentAccountAuthorization> Authorizations { get; set; }
        public virtual ICollection<TorrentAccountMessage> Messages { get; set; }
    }
}
