//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zen.Trunk.Torrent.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorrentAccountAuthorization
    {
        public System.Guid TorrentAccountAuthorizationId { get; set; }
        public System.Guid TorrentAccountId { get; set; }
        public System.Guid TorrentRemoteControlId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int AuthorizationState { get; set; }
    
        public virtual TorrentAccount Account { get; set; }
        public virtual TorrentRemoteControl RemoteControl { get; set; }
    }
}
