//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zen.Trunk.Torrent.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorrentRemoteControl
    {
        public TorrentRemoteControl()
        {
            this.Authorizations = new HashSet<TorrentAccountAuthorization>();
            this.Messages = new HashSet<TorrentRemoteControlMessage>();
        }
    
        public System.Guid TorrentRemoteControlId { get; set; }
        public string FriendlyName { get; set; }
        public string ClientAddress { get; set; }
        public string ClientAddressUpdateDate { get; set; }
        public RemoteControlDeviceType DeviceType { get; set; }
        public string SubscriberId { get; set; }
    
        public virtual ICollection<TorrentAccountAuthorization> Authorizations { get; set; }
        public virtual ICollection<TorrentRemoteControlMessage> Messages { get; set; }
    }
}
